---

- name: Prepare containers for global install testing
  hosts: all
  become: true
  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: true
      when: ansible_pkg_mgr == 'apt'
